### ISSUE TITLE
Problems while connected to a remote machine

### ISSUE THREAD

**Issue by marioloreti** [jmdaweb/NVDARemoteServer#11]
I am experiencing problems while connected to a remote machine. Sometimes, while I am working I ear the beep of NVDA Remote that indicates that someone is connected, then this person types some text to try some password like "user admin 123, pass bla bla", and then I ear the disconnect sound. After a few seconds, again I ear this exact sequence.
It seems that someone can connect to the server and to the machine, also if the password it's a bit complicated.
To temporarily try to solve the problem I shutdown NVDA before of disconnecting, but it's a bit unsecure I believe.

**Comment by jmdaweb** [comment]
Hello.
This issue will be fixed in version 1.6. I plan to add a log level setting to the options, so server administrator will decide which information is displayed (ip addresses, server errors, passwords, etc.).

**Comment by jmdaweb** [comment]
Added a new option in the latest commit which fixes this issue. Version 1.6 will be more secure.
