### ISSUE TITLE
When the NVDA client is killed by force and then try it connect again, the server crash [windows server 2008 R2]

### ISSUE THREAD

**Issue by RicCPT** [jmdaweb/NVDARemoteServer#13]
## Problem
When the NVDA client is killed by force and then try it connect again, the server crash.
I try execute the server in command line as admin or as windows service, but the problem maintain.

**Steps to reproduce the error**
1. start server "NVDARemoteServer.exe" (v1.4.2)
2. start nvda client in another machine (NVDARemote addon v2.1) 
3. kill nvda client process (taskkill /F /T /IM "nvda.exe")
4. start nvda client again

## Workaround
Execute server in debug mode :).
In debug mode the problem not occur.

## LOG file 'NVDARemoteServer.log' (timeline)
**Start server "NVDARemoteServer.exe" (v1.4.2) [Windows Server 2008 R2]**
> Loggin system initialized.
> Configuring signal handlers
> NVDA Remote Server is ready.
> The server is using TLS v 1.2
> The server is running with pid 16804

**Start NVDA client (NVDARemote addon v2.1) [Windows 10 Pro 64bit]**
> New incoming connection
> Setting socket options...
> Added a new client.
> Created new channel with passwordlbw12345
> Client 1 joined channel lbw12345

**Kill NVDA client (execute 'taskkill /F /T /IM "nvda.exe"')**
> Socket error in client 1 while receiving data
> Traceback (most recent call last):
>   File "server.py", line 314, in handle_data
>   File "ssl.pyo", line 766, in recv
>   File "ssl.pyo", line 653, in read
> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "threading.pyo", line 801, in __bootstrap_inner
>   File "server.py", line 255, in run
>   File "server.py", line 317, in handle_data
>   File "server.py", line 44, in printError
>   File "traceback.pyo", line 128, in print_exception
>   File "traceback.pyo", line 13, in _print
>   File "codecs.pyo"

**Start NVDA client again**
> , line 706, in write
>   File "codecs.pyo", line 369, in write
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 29: ordinal not in range(128)
> 
> New incoming connection
> Setting socket options...
> Added a new client.
> Traceback (most recent call last):
>   File "server.py", line 167, in run
>   File "server.py", line 330, in handle_data
>   File "server.py", line 349, in parse
>   File "server.py", line 371, in do_join
>   File "threading.pyo", line 730, in start
> RuntimeError: threads can only be started once
**[CRASH]**

Best regards,
Ricardo Carvalho
_ricardocarvalho@c-core.org_

**Comment by jmdaweb** [comment]
Hi Ricardo.
I have succesfully reproduced it. Thanks for reporting this issue, now it’s fixed.
Regards.


From: RicCPT
Sent: Sunday, August 13, 2017 4:27 AM
To: jmdaweb/NVDARemoteServer
Cc: Subscribed
Subject: [jmdaweb/NVDARemoteServer] When the NVDA client is killed by force and then try it connect again, the server crash [windows server 2008 R2] (#13)

Problem

When the NVDA client is killed by force and then try it connect again, the server crash.
I try execute the server in command line as admin or as windows service, but the problem maintain.

Steps to reproduce the error

  1.  start server "NVDARemoteServer.exe" (v1.4.2)
  2.  start nvda client in another machine (NVDARemote addon v2.1)
  3.  kill nvda client process (taskkill /F /T /IM "nvda.exe")
  4.  start nvda client again

Workaround

Execute server in debug mode :).
In debug mode the problem not occur.

LOG file 'NVDARemoteServer.log' (timeline)

Start server "NVDARemoteServer.exe" (v1.4.2) [Windows Server 2008 R2]

Loggin system initialized.
Configuring signal handlers
NVDA Remote Server is ready.
The server is using TLS v 1.2
The server is running with pid 16804

Start NVDA client (NVDARemote addon v2.1) [Windows 10 Pro 64bit]

New incoming connection
Setting socket options...
Added a new client.
Created new channel with passwordlbw12345
Client 1 joined channel lbw12345

Kill NVDA client (execute 'taskkill /F /T /IM "nvda.exe"')

Socket error in client 1 while receiving data
Traceback (most recent call last):
File "server.py", line 314, in handle_data
File "ssl.pyo", line 766, in recv
File "ssl.pyo", line 653, in read
Exception in thread Thread-2:
Traceback (most recent call last):
File "threading.pyo", line 801, in __bootstrap_inner
File "server.py", line 255, in run
File "server.py", line 317, in handle_data
File "server.py", line 44, in printError
File "traceback.pyo", line 128, in print_exception
File "traceback.pyo", line 13, in _print
File "codecs.pyo"

Start NVDA client again

, line 706, in write
File "codecs.pyo", line 369, in write
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 29: ordinal not in range(128)

New incoming connection
Setting socket options...
Added a new client.
Traceback (most recent call last):
File "server.py", line 167, in run
File "server.py", line 330, in handle_data
File "server.py", line 349, in parse
File "server.py", line 371, in do_join
File "threading.pyo", line 730, in start
RuntimeError: threads can only be started once
[CRASH]

Best regards,
Ricardo Carvalho
ricardocarvalho@c-core.org
