### ISSUE TITLE
error using nvda remote server for windows on windows 10 above aniversary update

### ISSUE THREAD

**Issue by vlad-a-c** [jmdaweb/NVDARemoteServer#17]
hi.
when i want to use nvda remote server on windows, any of the executables work just fine, but when i connect with a key and someone tries to connect my server restarts and it shows up in the logo some type of error like 10061 or something like that.

**Comment by jmdaweb** [comment]
Hi.

This is a known problem, and I am trying to discover why it happens.

Regards.

El 17/04/2018 a las 21:17, vlad-a-c escribió:

hi.
when i want to use nvda remote server on windows, any of the executables work just fine, but when i connect with a key and someone tries to connect my server restarts and it shows up in the logo some type of error like 10061 or something like that.

**Comment by jmdaweb** [comment]
Hello.
Do you remember this issue? After a long time, I'm working on it. I have a few questions:

* Can you still reproduce the issue?
* Can you reproduce the issue if you build a binary version with Python 2.7.15? If you don't know how to build, let me know so I upload a prebuilt one.
* Do you have added an exception to the Windows firewall or any third-party firewall you have?

Regards.
