### ISSUE TITLE
1.8 Unable to build on sentos7

### ISSUE THREAD

**Issue by blindndangerous** [jmdaweb/NVDARemoteServer#20]
When attempting to run the build script in the RHL7 folder, I get the following errors.
RPM build errors:                                                               
    File must begin with "/": GPLv2                                             
    File must begin with "/": LICENSE                                           
I think I found the license file, that's in the root directory, but I'm not sure where the second one is, or if this is the file it's referring to.

**Comment by blindndangerous** [comment]
Sorry, but that didn't fix it either.  I'm also seeing this line in the script.
+ /usr/lib/rpm/find-debuginfo.sh --strict-build-id /root/rpmbuild/BUILD/NVDARemoteServer-1.8
find: `debug': No such file or directory
This should be a fresh copy, should I delete and git clone it again?

**Comment by jmdaweb** [comment]
If you read "+ exit 0" in the last line, build is OK. The debug warning
doesn't mean anything here.

Regards.
