### ISSUE TITLE
Unable to connect to the server using my domain

### ISSUE THREAD

**Issue by slannon97** [jmdaweb/NVDARemoteServer#23]
I have a server running on Ubuntu 18.04 LTS. However, I cannot connect using my domain name. I have to use the IP address of my VPS. The domain works with any other server and website I host, so I don't understand what the issue is. Do I need to configure something else?

**Comment by jmdaweb** [comment]
Hello.
Do you have an IPV6 address too? Does this address point also to your domain? Do you use Cloudflare or similar services to protect your website?

**Comment by slannon97** [comment]
Hello,

I don't use Cloudflare and I don't have a web server running. My domain has an AAAA record that points to the IPv6 address of my Linode server. What else could it be? I don't have any IPv6 ports open because I don't have an eed for it. I protect the server with the ufw firewall.

**Comment by jmdaweb** [comment]
Hi,
Try opening the server port also for IPV6. If you want, tell me your domain and I'll perform some tests too.
Regards.

**Comment by slannon97** [comment]
I opened TCP port 6837 for IPv6 and it works correctly. Thank you.
