### ISSUE TITLE
No binaries?!

### ISSUE THREAD

**Issue by XP-Fan** [jmdaweb/NVDARemoteServer#24]
Hey, could you please provide some precompiled binaries for that? So that I have just one exe that I doubleclick and it works! I don't really want to install the whole python on my computer, nor do I think that I have enough knowledge and probably I'll fail anyway. I would as well have some fedora linux, but no idea how I could find out which docker-version I'm using. furthermore it could just be nice to have this as an NVDA-Addon? Aside from my fedora I'm on Windows XP btw...

**Comment by jmdaweb** [comment]
Hey, did you visit the releases page?

**Comment by XP-Fan** [comment]
Oh, sorry, I suck! I'm just not well with that github stuff and normally the projects I knew provided a link within their readme to their binaries... Anyway, thanks for your awesome work, and especially for maintaining XP-Compatibility!
