### ISSUE TITLE
The server.pem file does not seem to be updated after running sudo NVDARemoteCertificate

### ISSUE THREAD

**Issue by slannon97** [jmdaweb/NVDARemoteServer#25]
I am installing this server on Ubuntu 19.04. I managed to get the server running, but I am not sure if the SSL certificate is working properly. I ran the sudo NVDARemoteCertificate script and followed all the prompts. I was told a key was created, but the server.pem file located inside the NVDARemoteServer-master folder still says the last modified date is October 2018. Did the certificate creation process fail or does it store the file in another location?

I have modified the conf file to locate server.pem at the place where I extracted the folder, which is /home/chris/NVDARemoteServer-master/server.pem in my case. However, I would like to verify my newly created certificate is working properly. Is there an easy way to do this that does not require writing code?

**Comment by jmdaweb** [comment]
Hi,

Your modifications to the conf file are working properly. However, the server has been made to be installed, so you should build and install the .deb package (Debian8 in your case). Alternatively, you can download a prebuilt version from the releases page in this repository.

Regarding the new certificate, it should be located at /usr/share/NVDARemoteServer/server.pem

Regards.


El 10/09/2019 a las 4:53, slannon97 escribió:

I am installing this server on Ubuntu 19.04. I managed to get the server running, but I am not sure if the SSL certificate is working properly. I ran the sudo NVDARemoteCertificate script and followed all the prompts. I was told a key was created, but the server.pem file located inside the NVDARemoteServer-master folder still says the last modified date is October 2018. Did the certificate creation process fail or does it store the file in another location?

I have modified the conf file to locate server.pem at the place where I extracted the folder, which is /home/chris/NVDARemoteServer-master/server.pem in my case. However, I would like to verify my newly created certificate is working properly. Is there an easy way to do this that does not require writing code?

**Comment by slannon97** [comment]
Thank you for this information. So should I modify the conf file to point at /usr/share/NVDARemoteServer/server.pem?

**Comment by jmdaweb** [comment]
In this situation, I recommend replacing the server.pem file in your
program folder with the new generated one without modifying the
configuration.

Regards.

**Comment by jmdaweb** [comment]
While the certificate has read permissions, the program will be able to use it. In most situations, all files have read permissions, so don't worry. I'm not sure at all about how permission inheritance works when copying files, so I can't answer your question.
