### ISSUE TITLE
Server refuses to start on Debian 10 buster

### ISSUE THREAD

**Issue by mobeeniqbal** [jmdaweb/NVDARemoteServer#28]
I have just tried to install NVDA remote server 1.9 on a fresh install of debian 10 buster. I have encountered the following issues when trying to run as root,.

* When the install completes, the server runs fine. However, after running NVDARemoteServer enable and rebooting, the server does not start at all. Nothing is output to the log at this point. The only way I can get it to run at all is in debug mode.
* When trying to run NVDARemoteServer start as root, the following is output to the log file and the server fails to start:

Loggin system initialized.
Thu May 14 05:06:35 2020
Configuring signal handlers
Thu May 14 05:06:35 2020
Initialized instance variables
Thu May 14 05:06:35 2020
Socket created.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/share/NVDARemoteServer/server.py", line 234, in run
    self.createServerSocket(self.port, self.port6, self.bind_host, self.bind_host6)
  File "/usr/share/NVDARemoteServer/server.py", line 207, in createServerSocket
    self.server_socket = ssl.wrap_socket(self.server_socket, certfile=options.pemfile, server_side=True)
  File "/usr/share/NVDARemoteServer/server.py", line 50, in bar
    return func(*args, **kw)
  File "/usr/lib/python2.7/ssl.py", line 931, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 542, in __init__
    self._context.load_cert_chain(certfile, keyfile)
IOError: [Errno 13] Permission denied
Running as sudo makes no difference. Do I need to create a separate user for the server to run as? Previously I was able to run as root fine on Debian stretch.

**Comment by hamzalatif7** [comment]
Did you  do any configurations before you started the server for example   did you use the  script to genorate an rsa pair certificate  if so can you try to  uninstall and reinstall  nvda remote with the pem file that comes with the server to see if it starts. If it starts with the pem file  that is  with the cirt but not your generated one then it sounds like a permission problem  try chown chown nvdaremoteserver /usr/share/NVDARemoteServer.server.pem that should fix your problem.

**Comment by jmdaweb** [comment]
It's the first time I see a permission denied error when running as root. Do you have systemd installed? Do you get an error when running systemctl with no arguments?
The server works with its own user account. Do you get any error when installing the .deb package?
