### ISSUE TITLE
Automatically enabled after installation on Arch Linux

### ISSUE THREAD

**Issue by tech10** [jmdaweb/NVDARemoteServer#29]
At the moment, installs of NVDARemoteServer 1.9.1 on Arch Linux will automatically enable the server for starting on boot, and I think, even run the server as well. I received no indication of this happening in the background, and other servers I've installed don't automatically do this for me. It's fine for Debian and other operating systems that may automatically enable servers on installation, but I don't think this should be the case for Arch Linux. The user should be in control of such a thing, not package installation.

Keep it simple.

**Comment by jmdaweb** [comment]
Hi,
Although it is enabled by default, he server is not started after installation. I decided to enable it to make things easier for users. You can run `NVDARemoteServer disable` to disable the service at boot. I'm aware that Arch Linux services are disabled by default after installation, but I prefer to keep it enabled for now.
Regards.
