### ISSUE TITLE
Python Dependencies Missing on CentOS 8

### ISSUE THREAD

**Issue by blindgeek** [jmdaweb/NVDARemoteServer#30]
Every time I attempt to install via the ./build.sh command, I keep getting the error Dependencies missing Python needs to...I have both Python 2.7 and 3.6 versions on my system and I also changed the default alternatives --set python (version number). So I decided to use the docker version instead but I see no enough documentation about this. Like how can I change the certificate, can I access any configs...

**Comment by jmdaweb** [comment]
Have you tried running `dnf install python`? I will work on Centos 8 in a near future to make this server work in that system. Regarding Docker, only the listening interface and port can be changed for now. Certificates and other settings can't be modified, unless you use volumes and other related commands. I will update the documentation to explain it better.
Thanks.

**Comment by jmdaweb** [comment]
Hi,
The latest commits allow you to build a compatible rpm file for Centos 8. You must install Python 3.8. I will close this issue as soon as I update the documentation about Docker.
