### ISSUE TITLE
bug: The following error occurs after more than a day when running the NVDA REMOTE server with docker: stdout: IPV4 socket has not been createdstderr: Terminated

### ISSUE THREAD

**Issue by dingpengyu** [jmdaweb/NVDARemoteServer#31]
Test Environment :
System OpenWrt R20.9.15 Master (git-20.256.12360-1a54222)
docker version 19.03.12
log:
stdout: IPV4 socket has not been createdstderr: Terminated
cc @jmdaweb

**Comment by dingpengyu** [comment]
[log.txt](https://github.com/jmdaweb/NVDARemoteServer/files/5388421/log.txt)

**Comment by jmdaweb** [comment]
Hi,
Since this system is based on Linux and has a single TCP/IP stack, IPV4 socket can't be created once IPV6 socket has started listening. This is because IPV6 socket can also handle IPV4 connections, so this isn't the problem. Is Open WRT the system where you have installed Docker? Have you been able to connect to the server multiple times before the error? The attached log only shows one connection.
Regards.

**Comment by dingpengyu** [comment]
> Hi,
> Since this system is based on Linux and has a single TCP/IP stack, IPV4 socket can't be created once IPV6 socket has started listening. This is because IPV6 socket can also handle IPV4 connections, so this isn't the problem. Is Open WRT the system where you have installed Docker? Have you been able to connect to the server multiple times before the error? The attached log only shows one connection.
> Regards.
hello @jmdaweb 

Yes it can, openwrt is available with docker, I already compiled docker into the firmware when I compiled openwrt myself.

**Comment by dingpengyu** [comment]
Yes, openwrt is the system where docker is installed.
I was able to connect to the remote server normally before the error occurred.

**Comment by dingpengyu** [comment]
This is the docker image I use.
[jmdaweb/nvda-remote-server - Docker](https://hub.docker.com/r/jmdaweb/nvda-remote-server)

**Comment by jmdaweb** [comment]
Hi,
I have just uploaded new images for latest and 1.9 tags, so you can take advantage of the latest components and libraries. Could you please test it again and tell me how it works?
Regards.

**Comment by dingpengyu** [comment]
> Hi,
> I have just uploaded new images for latest and 1.9 tags, so you can take advantage of the latest components and libraries. Could you please test it again and tell me how it works?
> Regards.
hello @jmdaweb 
Thanks for your work, I'll update the docker image later and get back to you after testing.
