### ISSUE TITLE
Consider implementing nvda_not_connected

### ISSUE THREAD

**Issue by tech10** [jmdaweb/NVDARemoteServer#37]
The nvda_not_connected type is within the addon itself, but is not used in most servers. The server I wrote implements this, and it works quite well.

I believe the idea is this. If a master is connected to the server, but there are no slaves, and the master attempts to send a command to control a slave, keyboard, braille display, etc, the server should return json like this:

`{"type":"nvda_not_connected"}`

I've implemented it this way in my server, and I have found it to be quite valuable when a client is disconnected through connection interruption. Rather than silence when no slaves are connected to a channel, I get feedback from NVDA this way.

I hope this will be considered for inclusion.

**Comment by jmdaweb** [comment]
Hi,
Thank you very much for your idea. For now, I have decided to send this message only when there is a single client connected. Although multiple slaves or masters cannot control each other, they can perform actions such as sharing clipboard contents. Thush, the message won't be sent if multiple clients are connected to a channel.
Regards.
