### ISSUE TITLE
[Errno 98] Address already in use

### ISSUE THREAD

**Issue by dumbledad** [jmdaweb/NVDARemoteServer#38]
I cannot seem to get the server started on my Azure based Ubuntu VM. Here's the error message

`IPV6 socket created.
Sun Jul 11 15:46:10 2021
Setting socket options...
Sun Jul 11 15:46:10 2021
IPV6 socket cannot process incoming connections with the specified configuration. That means the configured interface and port are used by another application, or your system does not support IPV6. The server may still process incoming IPV4 connections
Sun Jul 11 15:46:10 2021
IPV4 socket created.
Sun Jul 11 15:46:10 2021
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/share/NVDARemoteServer/server.py", line 225, in run
    self.createServerSocket(self.port, self.port6, self.bind_host, self.bind_host6)
  File "/usr/share/NVDARemoteServer/server.py", line 213, in createServerSocket
    server_socket.bind((bind_host, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

Setting socket options...
Sun Jul 11 15:46:10 2021
IPV4 socket cannot process incoming connections with the specified configuration. In most situations, this means IPV6 socket will process incoming IPV4 connections, so you can ignore this message.
Closing logger thread...`

I ran nmap to ensure that the port is open, it is.

**Comment by jmdaweb** [comment]
Hi,
If NMap says the port is open, it means some application is listening on that port. Try restarting Ubuntu with the reboot command, and start the server again. If it still fails, try changing the port.
Hope it works.

**Comment by dumbledad** [comment]
Thanks, that worked!
