### ISSUE TITLE
error configgering signal handlers traceback

### ISSUE THREAD

**Issue by amirmahdifard** [jmdaweb/NVDARemoteServer#43]
so developer, i'm running nvda remote server in windows server as servis mode: sometimes i get so meny errors and traccebacks that i want you to fix them in next vertion of this: so by the way, i'm using the last vertion that in releeses section you put: this traceback happens everytime i start my servis
  Thu Dec  8 04:08:02 2022
  Configuring signal handlers
  Thu Dec  8 04:08:02 2022
  Error setting handler for signals
  Thu Dec  8 04:08:02 2022
  Traceback (most recent call last):
    File "server.py", line 586, in startAndWait
    File "signal.py", line 47, in signal
  ValueError: signal only works in main thread of the main interpreter
  this typed in my log when i start the servis: so please fix it.

**Comment by jmdaweb** [comment]
Hi,
There's nothing to fix. That trazeback is intentional and is raised when the server is started in service mode. You can safely ignore it. I'll consider removing it in the next release.
Regards.

**Comment by amirmahdifard** [comment]
@jmdaweb thank you for your attention: even if there is nothing to fix, please stil remove it so it doesn't make this error, because, in the log it shows traceback and a bunch of lines and an error: it's not good, so please remove it, i hope in the next vertion we have so less of these traceback, and i hope that we can have the next vertion that doesn't crash and doesn't stops the servis while running: this app is grate, just please work on it's stability more: thanks so much
