### ISSUE TITLE
please moove some files to another folder inside the main folder instead of leaving all of them inside the main folder

### ISSUE THREAD

**Issue by amirmahdifard** [jmdaweb/NVDARemoteServer#46]
@jmdaweb so bro, i really don't know how to compile some code my self, so i'm using the last vertion that you compile and put in releese's section for the windows platform: when i download this zip file and i extract it to use it, there is like 87 items in the main folder: i know that these .dll and .pid files are needed for the app to work correctly, but if it is possible for you to do this, please inside the main folder, make a lib folder or something, and at least moove all .dll files and .pid files to that folder, while working with the app, i only need a fue items, like servis mannager.cmd, debug.cmd, nvda remote server.exe, nvda remote server.log, nvda remote server.conf, and nvda remote server sertifiket.cmd: so if possible something like that to put all .dll and .pid files to one folder inside the main folder to reduse the items in the main folder, very thank you if you answer me and tell me if this is possible or not.

**Comment by jmdaweb** [comment]
Sorry, it's not possible.

**Comment by tech10** [comment]
@amirmahdifard It looks like every component required for the execution of the server, is included, which would mean you wouldn't have to install Python or other components to run the server on your Windows system. If you want something with less files, you can check out [my server](https://github.com/tech10/nvdaRemoteServer) which cannot run as a service like this one will. There may also be some other advantages and disadvantages for your use case, you'll have to compare them to know for sure.

**Comment by amirmahdifard** [comment]
@tech10 wow thank you, but y i can't run it in servis mode? servis mode is good

**Comment by tech10** [comment]
Programs written in Go are not designed to run as a service.

**Comment by amirmahdifard** [comment]
@tech10 then in this kace,  y you don't making it  in cpp if you thinking python is slo?

**Comment by tech10** [comment]
It's a lot harder to support multiple operating systems that way. We should probably not continue this discussion here, this isn't the place for it.

**Comment by amirmahdifard** [comment]
@tech10 yeah i agree that we shouldn't talk about it here, i was just saying, that i think that c pluss pluss is even stronger than go, and i think it supports servis mode too because teamtalk server side is coded on cpp and it supports to run it in servis mode

**Comment by amirmahdifard** [comment]
@tech10 and thank you for this server that you gave me: if it doesn't supports servis mode, that doesn't mean that i won't use it: i gladly downloaded it last night, and i will use it, and if there is a problem, i will open a tikit, and will let you know! thank you that you gave me a program that you've coded.
