### ISSUE TITLE
i cant use commandline options

### ISSUE THREAD

**Issue by MesterPerfect** [jmdaweb/NVDARemoteServer#47]
I'm trying to use command line here
for example
```
python3 options.py --motd="hello all"
```

```
python3 options.py ---certfile=/home/nvda/server.pem
```

It does not show any error, however, the message did not appear and it still shows the security warning when connected

**Comment by jmdaweb** [comment]
Hi,
You can't directly call options.py. Instead, run `python3 server.py debug --option1=value1 --option2=value2`
Please, before opening an issue, make sure you read and understand the provided documentation.
Regards.
