### ISSUE TITLE
some thorts to this project from me personally.

### ISSUE THREAD

**Issue by amirmahdifard** [jmdaweb/NVDARemoteServer#48]
ok, so hi everyone who reads this, of corce includes @jmdaweb too: so bro, i want to say somethings to you: first of all, i'm generally thinking that the project of nvda remote addon for nvda, is not really activ, and seems its developer has left the project or doesn't care about it, because he even doesn't care about some nice suggestions in the github repo: i'm sure if he actually activly worked on that project, we would've gotan a lot more bettar nvda remote addon:, but i feel that your project is upside down: even if it's not activ so much, at least it gets some commits at some point from you bro, and i onnistly else than this crashing problem, don't have any problems with this nvda relay server that you made, and as i see, you're already fixed the issues that i've reported about the crash, so i'm waiting for the next releace excitedly, and thank you for your fix: but here is my request to you that i would like to have: since this nvda relay server is so nice, and i already saw your pull requests that you've opened in the nvda remote addon a while ago, and you closed them because the developer didn't cared about them, wich i give you the right here: if i was the one who opened those pull requests, i would also close them if the developer was being that rood that didn't make any action for my pull requests: so, i think that you could get the nvda remote addon code as it is open source, and you can add it to this repo, and work on both of them in this repo: the relay for nvda remote, and the actual addon: so then this project will releace both nvda remote addon, and it's server side too, as teamtalk does such a thing for example: and if you do this, you can add a lot of features and improvements to the addon, and i would personally support it and use it: i beleave that there are a lot of good abilitys that can be added to the nvda remote addon, but as i said, apparently not with that developer: thank you for reading, you can comment your thorts under this tikit of corce: thanks.

**Comment by jmdaweb** [comment]
Hi,
Thanks for your comment. I plan releasing a new version once some deprecation warnings are fixed for Python 3.11, maintaining compatibility with version 2.7 if possible. There are some issues I can't reproduce, so I can't fix them.
From @nvda-es we have made a forked add-on, called TeleNVDA, which includes some enhancements, updated translations and releases updates regularly to make it compatible with new NVDA versions.
If you want to take a look, visit https://github.com/nvda-es/TeleNVDA
Unfortunately, I haven't time enough to actively work on it, but you can open issues and discuss them with all the community members.
Regards.

**Comment by amirmahdifard** [comment]
@jmdaweb hi, really thank you: i would gladly use it, but please, look at the main nvda remote github page, and see if you can develop my 2 suggestion that i opened? thank you so much if you can!
