### ISSUE TITLE
Memory usage going up once started.

### ISSUE THREAD

**Issue by blindndangerous** [jmdaweb/NVDARemoteServer#9]
Updated to 1.41.  I ran the build.sh script, and installed the .deb package.  All seems fine, until I run sudo nvdaremoteserver start.  When I watch htop, my ram usage goes up and doesn't stop, and I seem to have two instances of python going.  As soon as I kill nvdaremoteserver, my ram goes back to normal.  Any suggestions on what I could try?

**Comment by jmdaweb** [comment]
Hello.
This is a known Python bug. The memory is allocated, but never returns to the system when it is freed. Version 1.4 uses threads, so the memory is increased faster. If the memory limit is reached, the system kills the process. I'm going to work with the multiprocessing api, putting each channel in a separate process, but it will be difficult, the shared resources need to be managed properly.
You can go back to version 1.3, you will find the binaries in the releases page inside this repository.
Regards.

**Comment by blindndangerous** [comment]
ok.  I'll see if I can get that installed then.  Hope that you can fix 
this, as I like to stay current with things if I can.

**Comment by pvagner** [comment]
I can't prove this however I am afraid there must be some kind of evil memory leak somewhere. I understand that python may not always be able to release the memory or the script might be breaking its garbage collection in unexpected ways. However just for a test I have tried to run 1.4.1 on a memory constrained VPS (1GB of memory) and with some 30 minutes of running the VPS turned into such an unexpected state that even bash was unable to allocate memory for basic terminal work.
Even the fact by default it's configured to run as root when installed system wide at least with the provided arch linux package makes it even worse.
I'll try poking more at this during next few days.
I apologize for somewhat preliminary guess work.

**Comment by jmdaweb** [comment]
Hello.
Please, check this new server. I have performed some tests on Windows and the memory returns back to the system. If it works, let me know so I can close this issue.

**Comment by pvagner** [comment]
Hello,
Yeah, thank you, todays commit improves the overal experience.
I was looking for some 30 minutes watching how channels were created, destroyed and checked with the helper threads. I was even able to notice small memory changes as threads were spawned / finished.
So I would consider this as being fixed.
However I am afraid there is another issue related to the current implementation. For each new channel NVDARemoteServer spawns a new thread running seperate infinite loop for handling incoming network traffic.
As these loops are running in paralel I think it significantly affects CPU usage.
For example I do have two single core CPUs on the VPS where I'm currently running NVDARemoteServer. When NVDARemoteServer is stopped CPU usage is very close to 0. As NVDA remote server is running with four channels cpu column in the ps output shows about 136 % for NVDARemoteServer. When running three channels it shows more than 100% although it's a bit less than 136.
What are your experiences? How many clients or channels are you confortable running this with?

**Comment by jmdaweb** [comment]
Hello.
I haven't tested it on a server with many users, so your feedback is very important. Each loop only takes into account the sockets that are in the current channel, I don't know at this time how to make the server more eficient. Some time ago I tried to make another implementation, where there was a thread per client. Unfortunately, the collisions and race conditions were too much, so I didn't commit it to the repository.

**Comment by borris84** [comment]
Related; I'm noticing exceptionally high CPU usage with 1.41, even with only one client thread active. Tested on a Raspberry Pi and a dual CPU core VPS, both running Debian 8.
CPU usage seems to constantly hang out around the 100% usage mark (Python is currently at 99.8%) on the VPS with a single client connected. I usually have four clients connected to my server at all times, and the number is still consistent when adding clients. Memory consumption doesn't seem to be an issue currently.

**Comment by jmdaweb** [comment]
Hello.
Try the latest version from the repo, it should be fixed.
Regards.
